### ISSUE TITLE
Busser only uses /tmp/verfier/gems as it's local source

### ISSUE THREAD

**Issue by damacus** [test-kitchen/busser#27]
I'd like to be able to reduce my spin up the verify times of kitchen suites. 
Baking the busser/busser-serverspec etc gems into the chef omnibus installer would be a nice option as it will persist between destroys. 
I there a way to override the BUSSER_GEM, GEM_PATH, GEM_HOME, GEM_CAHE variables?

Assuming that: 
- chef-client is installed into the image
- busser and busser-serverspec gems are installed 

kitchen would find those gems. For a slow connection, or a non-existent connection to the internet (corp firewall, no-internet etc) this would be super useful. 

If this doesn't belong here, but in the kitchen-ci repo I'm happy to move it.

**Comment by blelump** [comment]
I've got a similar issue so  I've dived into the code and it seems it's more related to [test-kitchen][1] itself. As these variables are configured [here][2] and they're all based on `root_path` value, they might be slightly configured, eg.

```
# .kitchen.yml
busser:
  root_path: /some/path
```

However, in my case it doesn't solve anything, since I would like to use simply environment Ruby and gems. Besides, the [installation script][3] is also interesting, because it never checks for system libraries as the `GEM_PATH` is set to `[root_path, "gems"]` whereas `root_path` by default points to `/tmp/verifier`.

If you're provisioning the environment anyhow, I suggest to just put whatever is needed into `root_path`, because it seems it's the easiest solution here.

[1]: https://github.com/test-kitchen/test-kitchen
[2]: https://github.com/test-kitchen/test-kitchen/blob/5e4fa6baff5d51dc983be3f7b67ffe1bcbf2a8d2/lib/kitchen/verifier/busser.rb#L144
[3]: https://github.com/test-kitchen/test-kitchen/blob/master/support/busser_install_command.sh

**Comment by damacus** [comment]
I don't think I/we need this anymore with inspec/improvements to train. I certainly can't replicate it anymore.
