### ISSUE TITLE
test group(plugin) priority

### ISSUE THREAD

**Issue by Alukardd** [test-kitchen/busser#34]
It will be great if I can specify plugins execution order.

For example `test/integration/default/00_serverspec` and `test/integration/default/01_bats`. Because I want that first of all my chef cookbook will be tested on serverspec and if all ok, then I want to do more complex tests with bats.

Thanks.

**Comment by cheeseplus** [comment]
What is the use case in which you are using two different test frameworks? This is potentially something I can get behind supporting but curious if it's something necessary for the specific use case.

**Comment by Alukardd** [comment]
Ok, for example:
I have cookbook-nginx, and I want to test it. I want to check:
- is nginx package is installed;
- is nginx service is enabled and running;
- is is nginx listen on tcp/80 port;
- is nginx answer properly for "GET /" request.

And of course, I can write all this tests on bash (bats), but if I want to test cookbook on different platforms (debian and redhat). And serverspec give abstraction on package system(dpkg, rpm) and init system(Sys V Init, Upstart, Systemd). And I wont to write "switch case" on bash for check all this cases.
But for more complex check like last, I should use curl and others external tools.

**Comment by cheeseplus** [comment]
I'd suggest giving a look at InSpec or Rspec or minitest for doing covering all of your tests instead of breaking them up between two frameworks. They can use external tools and keep you inside a better abstraction as you mention with the ability to case by OS or platform version.

This feature is still something we can look given that this can be done without testing two different frameworks it's going to be something low priority unless someone wants to work on a PR for it.
